name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: peaceiris/actions-mdbook@v1
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      # must run mdbook test right after `cargo build` or it fails to find the crate
      - name: mdbook test
        run: mdbook test chorus_book -L ./target/debug/deps
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  publish-book:
    runs-on: ubuntu-22.04
    needs: ["build-and-test"]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-mdbook@v1
      - run: mdbook build chorus_book
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./chorus_book/book
